var choices_data = [
  {
    choice_num: 1,
    choice_option_01: "draw",
    choice_option_02: "drawn",
    next_choice_num_01: 2,
    next_choice_num_02: 3,
    choice_option_01_line: "you could look a river in the throat and still read its lips",
    choice_option_02_line: "you could look a river in the throat and still read its lips",
    image: "",
    placement: "",
    opacity: 0.1,
  },
  {
    choice_num: 2,
    choice_option_01: "dive",
    choice_option_02: "dove",
    next_choice_num_01: 4,
    next_choice_num_02: 5,
    choice_option_01_line: "come spring, your steps will bring breath to the mud and the suds will shine effervescent with the tilted sun.",
    choice_option_02_line: "you gave awakening a stern talking to behind the thin winter brush. it scrambled with the bird song, just stressed enough to make the branches creak as it fled to its center.",
    image: "",
    placement: "",
    opacity: .25,
  },
  {
    choice_num: 3,
    choice_option_01: "path",
    choice_option_02: "pave",
    next_choice_num_01: 6,
    next_choice_num_02: 7,
    choice_option_01_line: "the garden in your jaw bone has been kept still. only the trellis wobbles with the vines weight, the stretches of budding.",
    choice_option_02_line: "while unseelie pinch your ankles, you tend to the ghost of a flower, lost in the pluckiness of its outline.",
    image: "",
    placement: "",
    opacity: .25,
  },
  {
    choice_num: 4,
    choice_option_01: "slip",
    choice_option_02: "sink",
    next_choice_num_01: 8,
    next_choice_num_02: 8,
    choice_option_01_line: "when offered to be the susurrus between a copse of trees, you firmly pierced the crepuscular rays and lit our home with light kebabs. you can bend them like goosenecks and you have a specific arrangement for when you put pencil to paper.",
    choice_option_02_line: "an old photocopier in the creekbed turns out linocuts of your legend.",
    image: "",
    placement: "",
    opacity: .5,
  },
  {
    choice_num: 5,
    choice_option_01: "feel",
    choice_option_02: "find",
    next_choice_num_01: 9,
    next_choice_num_02: 9,
    choice_option_01_line: "as your gaze traces a path, the serpent perches and crevices swell with coiled vines, the reaping of touch and passion.",
    choice_option_02_line: "any blanched sky, with creeping silhouettes like thank you card fringes, is marbled with your aura. a frog eye squints and unframes the atmospheric veins.",
    image: "",
    placement: "",
    opacity: .5,
  },
  {
    choice_num: 6,
    choice_option_01: "soak",
    choice_option_02: "seize",
    next_choice_num_01: 10,
    next_choice_num_02: 10,
    choice_option_01_line: "some say the crusts of shadows pass a softened reverence. the holy crispness in your grace.",
    choice_option_02_line: "you could ruffle the feathers of any nightmare. pupils of polished shedua, of a timber study and its lignin rot and its labored experience and its underbelly gently pushed on by mush caps.",
    image: "",
    placement: "",
    opacity: .5,
  },
  {
    choice_num: 7,
    choice_option_01: "know",
    choice_option_02: "knit",
    next_choice_num_01: 11,
    next_choice_num_02: 11,
    choice_option_01_line: "it’s guaranteed our home will be swallowed by the churning soil. the spirit of you spins faster than time.",
    choice_option_02_line: "creatures and their coats parade in the current of your curiosity, a cozy stroll. and they strut too. it’s a feast for all the lines in the world to come and devour. we wove a carpet for them out of the gifted silk from the shadow crusts.",
    image: "",
    placement: "",
    opacity: .5,
  },
  {
    choice_num: 8,
    choice_option_01: "hymn",
    choice_option_02: "hum",
    next_choice_num_01: 12,
    next_choice_num_02: 12,
    choice_option_01_line: "a wolf of two coats offers one to you and begins to prepare tea. the steam conga lines through the wood. the wilds are yours and yours alone.",
    choice_option_02_line: "in a robin’s nest made of bookmarks, you are the page saved across tomes and the warmth held to make homes.",
    image: "",
    placement: "",
    opacity: .7,
  },
  {
    choice_num: 9,
    choice_option_01: "bask",
    choice_option_02: "bake",
    next_choice_num_01: 12,
    next_choice_num_02: 12,
    choice_option_01_line: "once, a self tugged on your skirt. she looked up at you dwarfed by concrete. you crouched down, and as you lowered, the walls melted before infinite forests. you held her glassy eyes with your misty ones and said, 'there will always be a seed growing somewhere'",
    choice_option_02_line: "a cast iron wriggles into the fire. there is an itch to cozy against everything you make.",
    image: "",
    placement: "",
    opacity: .7,
  },
  {
    choice_num: 10,
    choice_option_01: "aim",
    choice_option_02: "ask",
    next_choice_num_01: 12,
    next_choice_num_02: 12,
    choice_option_01_line: "when you invited the ants in decorously, they offered to make you a pillow. they worked in the night as you tossed and turned to reform and swap warm grains for cool ones. these little bows of effort define the grace of your scraps.",
    choice_option_02_line: "a few walking sticks crossed paths and when you took their bridge, they stopped feeling rigid. they let loose enough so you could walk on the water’s surface.",
    image: "",
    placement: "",
    opacity: .7,
  },
  {
    choice_num: 11,
    choice_option_01: "gain",
    choice_option_02: "give",
    next_choice_num_01: 12,
    next_choice_num_02: 12,
    choice_option_01_line: "there are wings being blown off like dandelion florets, and the angels crater into the ground around you, forming a field of puddles.",
    choice_option_02_line: "all evening skies are lightened by the promise of morning sun falling on your smile.",
    image: "",
    placement: "",
    opacity: .7,
  },
  {
    choice_num: 12,
    choice_option_01: "begin",
    choice_option_02: "end",
    next_choice_num_01: 1,
    next_choice_num_02: 1,
    choice_option_01_line: "the hum and surges of earth forever pass at your heart and i am so grateful to share in our soft world’s regard.",
    choice_option_02_line: "the hum and surges of earth forever pass at your heart and i am so grateful to share in our soft world’s regard.",
    image: "",
    placement: "",
    opacity: 0,
  },
]
