let questions = [
    {
        Order: NaN,
        Category: "Condition",
        Question: "Are you involved with active judicial proceedings",
        Constraint: "Delays and Endurance of the Flawed Justice System",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Do you receive most of your basic needs from the market? for example, do you get health insurance from private corporations, do you rent your home, do you get your food from major grocery chains?",
        Constraint: "Basic Needs Markets Infected by Greed (Housing, Healthcare, etc.)",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Are you at risk of prosecution?",
        Constraint: "Act and Threat of Imprisonment",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Are you at risk of losing your home, not having enough food this month, or not being able to get healthcare?",
        Constraint: "Lack of Safety Nets and Stability of Core Needs",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Are there conditions that make traveling difficult? For example, does it hurt to move, do you not own a mode of transportation, does your area not have public transit, or do you live in a remote area?",
        Constraint: "Travel Distance and Difficulty",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Does you health prevent you from making plans or taking part in group activities?",
        Constraint: "Healthcare and Quality of Life",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Is it hard for you to trust the information you get online or otherwise?",
        Constraint: "Misinformation",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Is it expensive or difficult to communicate with others?",
        Constraint: "Cost of Communication",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Do you ever experience prejudice, discrimination, or harassment?",
        Constraint: "Prejudice and Discrimination",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Do you have relationships that don't make you feel safe?",
        Constraint: "Harmful Relationships",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Is it easy for you to be entertained at home?",
        Constraint: "Accessibility of Entertainment",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Do you sell things for a living or do you rely on buying materials for your livelihood?",
        Constraint: "Consumption + Market Participation",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Is it easier to stay inside than to go meet friends or family in public?",
        Constraint: "Ease and Abundance of Isolation",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Do you fill out paperwork at least once every 2 weeks? For example, for doctor's appointments, state or federal benefits, legal documents, or contracts",
        Constraint: "Bureaucracy",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Would it cost you too much money to take a class and learn a new skill?",
        Constraint: "Cost of Knowledge",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Would losing your job mean poverty for you?",
        Constraint: "Employment + Threat of Poverty",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Do you regularly experience the unchecked greed of others?",
        Constraint: "Lack of Justice and Accountability from the Wealthy",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Do you have to make phone calls, write down lists, visit a professional, or search for information at least 3 times a week?",
        Constraint: "Administrative Burden",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Do you have a dependent, a child or an older person, that you have to care for?",
        Constraint: "Dependent Care + Caretaking",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Is it difficult to relax when something stressful happens?",
        Constraint: "Lack of Emotional Regulation",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Is it hard to think of a place that you could go and sit for free and meet people that you've never met before?",
        Constraint: "Lack of 3rd Spaces",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "If you use social media or algorithmic content applications, do you feel like you get similar information about world events without seeing anything new?",
        Constraint: "Algorithmic Feeds and Bias",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Do you feel like the articles, news, television, and media you read, listen, or watch are cynical or say there is no hope?",
        Constraint: "Media Tone and Content",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Would it be difficult to compare the current world to history and past events?",
        Constraint: "Lack of Perspective and Relevant History",
        Skill: NaN,
    },
    {
        Order: NaN,
        Category: "Condition",
        Question: "Does seeing other people in pain or hurting make it impossible for you to keep doing what you were doing?",
        Constraint: "Empathy of Exposure and Proximity to Pain",
        Skill: NaN,
    },
    {
        Order: "T00",
        Category: "Time",
        Question: "Could you find 2 hours of your day at home to sacrifice for one day each week?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "T01",
        Category: "Time",
        Question: "Could you find 2 hours of your day away from home to sacrifice for one day each week?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "T02",
        Category: "Time",
        Question: "Could you find 5 hours of your day at home to sacrifice for one day each week?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "T03",
        Category: "Time",
        Question: "Could you find 5 hours of your day away from home to sacrifice for one day each week?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "T04",
        Category: "Time",
        Question: "Could you find 8 hours of your day at home to sacrifice for one day each week?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "T05",
        Category: "Time",
        Question: "Could you find 8 hours of your day away from home to sacrifice for one day each week?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "T06",
        Category: "Time",
        Question: "Could you find 20 hours to spare across 1 week?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "T07",
        Category: "Time",
        Question: "Could you find 40 hours to spare across 1 week?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "T08",
        Category: "Time",
        Question: "Could you find 4 hours to give at the same time every week",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "T09",
        Category: "Time",
        Question: "Could you find several days of 4 hours to give at the same time every week",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "R00",
        Category: "Resource",
        Question: "Could you spend an extra $50 today without too much difficulty?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "R01",
        Category: "Resource",
        Question: "Could you spend an extra $200 this week without too much difficulty?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "R02",
        Category: "Resource",
        Question: "Could you spend an extra $1000 this month without too much difficulty?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "R03",
        Category: "Resource",
        Question: "Could you spend an extra $6000 this year without too much difficulty?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "R04",
        Category: "Resource",
        Question: "Are you able to put $50 in savings each week?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "R05",
        Category: "Resource",
        Question: "Are you able to put $200 in savings each week?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "R06",
        Category: "Resource",
        Question: "Do you have access to enough ground where you live for a garden?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "R07",
        Category: "Resource",
        Question: "Are you able to easily obtain loans?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "R08",
        Category: "Resource",
        Question: "Are you able to increase your income when needed?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "R09",
        Category: "Resource",
        Question: "Do you have enough savings to live for 3 months?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "S00",
        Category: "Skill",
        Question: "Do you have technical skills that could help your neighbor, like auto mechanic skills, plumbing, sewing, computer skills, gardening, spoken language, etc.?",
        Constraint: NaN,
        Skill: "Technical Skills",
    },
    {
        Order: "S01",
        Category: "Skill",
        Question: "Are you able to break down tasks and keep an organized checklist?",
        Constraint: NaN,
        Skill: "Task Management and Task Deconstruction",
    },
    {
        Order: "S02",
        Category: "Skill",
        Question: "When you get new information, is it easy for you to organize that information and ask questions about it?",
        Constraint: NaN,
        Skill: "Organizing New Information",
    },
    {
        Order: "S03",
        Category: "Skill",
        Question: "Do you have a clear vision of what a better world would look like?",
        Constraint: NaN,
        Skill: "Vision and Ideological State",
    },
    {
        Order: "S04",
        Category: "Skill",
        Question: "Can you stay calm during stressful situations and conflict",
        Constraint: NaN,
        Skill: "Emotional Health and Conflict Resolution",
    },
    {
        Order: "S05",
        Category: "Skill",
        Question: "Can you assess needs and reject excess?",
        Constraint: NaN,
        Skill: "Organized Divestment",
    },
    {
        Order: "S06",
        Category: "Skill",
        Question: "Can you share conflicting opinions and win over other people?",
        Constraint: NaN,
        Skill: "Debate and Ideological Competition",
    },
    {
        Order: "S07",
        Category: "Skill",
        Question: "Can you form connections with strangers and earn their support of you?",
        Constraint: NaN,
        Skill: "Connection and Campaigning",
    },
    {
        Order: "S08",
        Category: "Skill",
        Question: "Can you easily research new ideas, discover novel information, and learn new concepts?",
        Constraint: NaN,
        Skill: "Research, Discovery, and Knowledge Acquisition",
    },
    {
        Order: "S09",
        Category: "Skill",
        Question: "Do you have a strong sense of self and feel confident in your role?",
        Constraint: NaN,
        Skill: "Sense of Self/Role",
    },
    {
        Order: "S10",
        Category: "Skill",
        Question: "Are you physically strong, mobile, and flexible?",
        Constraint: NaN,
        Skill: "Physical Strength, Mobility, and Flexibility",
    },
    {
        Order: "N00",
        Category: "Network",
        Question: "Do your friends, family and co-workers have more resources?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "N01",
        Category: "Network",
        Question: "Do your friends, family and co-workers have more time?",
        Constraint: NaN,
        Skill: NaN,
    },
    {
        Order: "N02",
        Category: "Network",
        Question: "Do your friends, family and co-workers have more skills?",
        Constraint: NaN,
        Skill: NaN,
    }
]
