let tasklvl1 = [
    {
        "Task": "A time-saving favor",
        "Path Category": "Material gains for workers",
        "Scale": 2.38,
        "Skills": "SP,ME,TC",
        "Skill Cost": 1.146,
        "Solvability": 4.612,
        "Neglectedness": -5.5,
        "Impact Score": 0.35,
        "Time Score": 4.0,
        "Resource Cost": 2
    },
    {
        "Task": "A money-saving gift",
        "Path Category": "Material gains for workers",
        "Scale": 9.3,
        "Skills": "T,R,CV",
        "Skill Cost": 1.0,
        "Solvability": 5.0,
        "Neglectedness": -5.35,
        "Impact Score": 7.95,
        "Time Score": 9.2,
        "Resource Cost": 9
    },
    {
        "Task": "Organizing and fundraising for non-hierarchical and engaging mutual aid",
        "Path Category": "Material gains for workers",
        "Scale": 9.57,
        "Skills": "V,MO,ECDS",
        "Skill Cost": 1.839,
        "Solvability": 6.069,
        "Neglectedness": -4.7,
        "Impact Score": 9.1,
        "Time Score": 7.5,
        "Resource Cost": 5
    },
    {
        "Task": "A repair/fix of a needed tool",
        "Path Category": "Material gains for workers",
        "Scale": 4.64,
        "Skills": "LPT,MRT,T",
        "Skill Cost": 1.114,
        "Solvability": 6.0,
        "Neglectedness": -4.85,
        "Impact Score": 4.68,
        "Time Score": 5.2,
        "Resource Cost": 4
    },
    {
        "Task": "Cooking and sharing a meal",
        "Path Category": "Material gains for workers",
        "Scale": 3.26,
        "Skills": ",P,M",
        "Skill Cost": 0.301,
        "Solvability": 4.597,
        "Neglectedness": -5.65,
        "Impact Score": 1.91,
        "Time Score": 5.52,
        "Resource Cost": 6
    },
    {
        "Task": "Teaching/learning a skill or sharing/growing knowledge",
        "Path Category": "Material gains for workers",
        "Scale": 9.73,
        "Skills": ",CME,TRO",
        "Skill Cost": 1.556,
        "Solvability": 7.153,
        "Neglectedness": -5.85,
        "Impact Score": 9.48,
        "Time Score": 5.91,
        "Resource Cost": 2
    },
    {
        "Task": "Create/operate a library, storage site, or communal repository",
        "Path Category": "Material gains for workers",
        "Scale": 9.48,
        "Skills": ",RVC,MOL",
        "Skill Cost": 1.556,
        "Solvability": 7.65,
        "Neglectedness": -5.0,
        "Impact Score": 10.57,
        "Time Score": 8.82,
        "Resource Cost": 5
    },
    {
        "Task": "Share a moment, an emotional release",
        "Path Category": "Organized Divestment",
        "Scale": 2.23,
        "Skills": ",D,VECS",
        "Skill Cost": 1.813,
        "Solvability": 6.382,
        "Neglectedness": -4.5,
        "Impact Score": 2.3,
        "Time Score": 4.58,
        "Resource Cost": 1
    },
    {
        "Task": "Develop and activate task/time management tools",
        "Path Category": "Material gains for workers",
        "Scale": 7.7,
        "Skills": ",RC,MOL",
        "Skill Cost": 1.491,
        "Solvability": 4.855,
        "Neglectedness": -4.5,
        "Impact Score": 6.57,
        "Time Score": 6.41,
        "Resource Cost": 3
    },
    {
        "Task": "Provide healthcare and healing services",
        "Path Category": "Material gains for workers",
        "Scale": 3.75,
        "Skills": "C,E,T",
        "Skill Cost": 0.477,
        "Solvability": 15.078,
        "Neglectedness": -7.0,
        "Impact Score": 11.35,
        "Time Score": 9.2,
        "Resource Cost": 8
    },
    {
        "Task": "Give, trade, or share items with neighbors",
        "Path Category": "Material gains for workers",
        "Scale": 1.3,
        "Skills": ",,CE",
        "Skill Cost": 0.903,
        "Solvability": 5.38,
        "Neglectedness": -5.5,
        "Impact Score": 0.28,
        "Time Score": 0.0,
        "Resource Cost": 7
    },
    {
        "Task": "Organize and attend resource fairs, like farmer's markets, for giving money to producers",
        "Path Category": "Organized Divestment",
        "Scale": 3.44,
        "Skills": ",,MC",
        "Skill Cost": 0.903,
        "Solvability": 7.153,
        "Neglectedness": -5.85,
        "Impact Score": 3.84,
        "Time Score": 5.59,
        "Resource Cost": 6
    },
    {
        "Task": "Look into ways to vertically integrate processes that avoid capitalists",
        "Path Category": "Organized Divestment",
        "Scale": 4.7,
        "Skills": "MC,R,O",
        "Skill Cost": 0.602,
        "Solvability": 9.562,
        "Neglectedness": -4.35,
        "Impact Score": 9.31,
        "Time Score": 4.0,
        "Resource Cost": 3
    },
    {
        "Task": "Form tenants unions",
        "Path Category": "Collective Ownership",
        "Scale": 5.0,
        "Skills": "S,VEC,CMO",
        "Skill Cost": 1.568,
        "Solvability": 8.773,
        "Neglectedness": -4.15,
        "Impact Score": 8.05,
        "Time Score": 8.7,
        "Resource Cost": 2
    },
    {
        "Task": "Form workers unions",
        "Path Category": "Collective Ownership",
        "Scale": 4.0,
        "Skills": "S,VEC,CMO",
        "Skill Cost": 1.568,
        "Solvability": 9.562,
        "Neglectedness": -5.5,
        "Impact Score": 6.49,
        "Time Score": 7.82,
        "Resource Cost": 2
    },
    {
        "Task": "Make connections, form peer-support and other organized networks",
        "Path Category": "Collective Ownership",
        "Scale": 2.0,
        "Skills": ",SV,CE",
        "Skill Cost": 1.079,
        "Solvability": 5.47,
        "Neglectedness": -4.85,
        "Impact Score": 1.54,
        "Time Score": 4.0,
        "Resource Cost": 1
    },
    {
        "Task": "Install security systems and measures for physical/cyber/communication environments",
        "Path Category": "Organized Divestment",
        "Scale": 9.09,
        "Skills": ",C,TMO",
        "Skill Cost": 1.447,
        "Solvability": 3.074,
        "Neglectedness": -4.44,
        "Impact Score": 6.28,
        "Time Score": 7.61,
        "Resource Cost": 6
    },
    {
        "Task": "Check in on comrades, ask to support and conduct needs assessments",
        "Path Category": "Democratized Use of Resources",
        "Scale": 6.79,
        "Skills": "MO,S,EC",
        "Skill Cost": 1.041,
        "Solvability": 7.282,
        "Neglectedness": -5.5,
        "Impact Score": 7.53,
        "Time Score": 5.2,
        "Resource Cost": 1
    },
    {
        "Task": "Distribute literature",
        "Path Category": "Organized Divestment",
        "Scale": 6.7,
        "Skills": "RTPMS,O,C",
        "Skill Cost": 0.845,
        "Solvability": 4.558,
        "Neglectedness": -4.85,
        "Impact Score": 5.57,
        "Time Score": 5.2,
        "Resource Cost": 5
    },
    {
        "Task": "Pool resources and finances for project-scaling",
        "Path Category": "Collective Ownership",
        "Scale": 9.94,
        "Skills": ",OE,MVC",
        "Skill Cost": 1.491,
        "Solvability": 8.305,
        "Neglectedness": -4.85,
        "Impact Score": 11.9,
        "Time Score": 4.0,
        "Resource Cost": 9
    },
    {
        "Task": "Send letters of support and connection to people in prison or detention",
        "Path Category": "Democratized Use of Resources",
        "Scale": 2.0,
        "Skills": "V,S,EC",
        "Skill Cost": 1.0,
        "Solvability": 8.584,
        "Neglectedness": -4.35,
        "Impact Score": 5.23,
        "Time Score": 4.32,
        "Resource Cost": 2
    },
    {
        "Task": "Organize and attend places for display (art, music, tools, etc.)",
        "Path Category": "Collective Ownership",
        "Scale": 4.6,
        "Skills": "ES,,MVC",
        "Skill Cost": 1.462,
        "Solvability": 4.0,
        "Neglectedness": -6.5,
        "Impact Score": 0.64,
        "Time Score": 3.11,
        "Resource Cost": 1
    },
    {
        "Task": "Collect and record histories and experiences",
        "Path Category": "Collective Ownership",
        "Scale": 10.6,
        "Skills": "SR,VE,TOC",
        "Skill Cost": 1.519,
        "Solvability": 5.0,
        "Neglectedness": -5.85,
        "Impact Score": 8.23,
        "Time Score": 5.2,
        "Resource Cost": 2
    },
    {
        "Task": "Coordinate, draft, and public processes and practices",
        "Path Category": "Organized Divestment",
        "Scale": 11.65,
        "Skills": "SE,DCR,MOVL",
        "Skill Cost": 1.875,
        "Solvability": 7.153,
        "Neglectedness": -4.85,
        "Impact Score": 12.08,
        "Time Score": 5.91,
        "Resource Cost": 1
    },
    {
        "Task": "Develop anti-greed self-governance systems and deploy them",
        "Path Category": "Organized Divestment",
        "Scale": 11.66,
        "Skills": ",,TMOLCR",
        "Skill Cost": 2.334,
        "Solvability": 7.65,
        "Neglectedness": -6.0,
        "Impact Score": 10.97,
        "Time Score": 5.2,
        "Resource Cost": 1
    },
    {
        "Task": "Improve then leverage self-governance systems as bargaining for greater resource sharing",
        "Path Category": "Democratized Use of Resources",
        "Scale": 12.66,
        "Skills": "R,S,CMOVELD",
        "Skill Cost": 2.538,
        "Solvability": 11.555,
        "Neglectedness": -5.0,
        "Impact Score": 16.67,
        "Time Score": 5.91,
        "Resource Cost": 1
    },
    {
        "Task": "Demonstrate and install anti-greed self-governance regulations at the policy level (official or otherwise)",
        "Path Category": "Policies Preventing Greed",
        "Scale": 14.56,
        "Skills": ",S,TMOVELDCR",
        "Skill Cost": 2.863,
        "Solvability": 13.523,
        "Neglectedness": -5.0,
        "Impact Score": 20.22,
        "Time Score": 8.32,
        "Resource Cost": 3
    },
    {
        "Task": "Buy homes, land, or multi-unit housing",
        "Path Category": "Collective Ownership",
        "Scale": 4.27,
        "Skills": "R,,MOC",
        "Skill Cost": 1.447,
        "Solvability": 38.734,
        "Neglectedness": -5.2,
        "Impact Score": 36.36,
        "Time Score": 8.82,
        "Resource Cost": 9
    },
    {
        "Task": "Organize and fight for shared ownership for workers starting with benefits/produced goods/services",
        "Path Category": "Collective Ownership",
        "Scale": 5.7,
        "Skills": "S,,MOVEDC",
        "Skill Cost": 2.336,
        "Solvability": 16.61,
        "Neglectedness": -6.0,
        "Impact Score": 13.97,
        "Time Score": 6.41,
        "Resource Cost": 1
    },
    {
        "Task": "Offer protection or legal support against current fascists and capitalist abuses",
        "Path Category": "Organized Divestment",
        "Scale": 7.33,
        "Skills": "S,ECDLR,TV",
        "Skill Cost": 1.531,
        "Solvability": 27.045,
        "Neglectedness": -4.85,
        "Impact Score": 27.99,
        "Time Score": 8.32,
        "Resource Cost": 4
    },
    {
        "Task": "Support care for dependents or share responsibilities",
        "Path Category": "Material gains for workers",
        "Scale": 1.75,
        "Skills": ",O,M",
        "Skill Cost": 0.301,
        "Solvability": 15.078,
        "Neglectedness": -6.35,
        "Impact Score": 10.18,
        "Time Score": 8.82,
        "Resource Cost": 2
    },
    {
        "Task": "Create and display art",
        "Path Category": "Collective Ownership",
        "Scale": 4.83,
        "Skills": "SEC,,TMV",
        "Skill Cost": 1.477,
        "Solvability": 7.153,
        "Neglectedness": -6.5,
        "Impact Score": 4.0,
        "Time Score": 8.82,
        "Resource Cost": 5
    },
    {
        "Task": "Create rituals for community belonging",
        "Path Category": "Organized Divestment",
        "Scale": 4.7,
        "Skills": ",SE,TVC",
        "Skill Cost": 1.491,
        "Solvability": 7.153,
        "Neglectedness": -5.2,
        "Impact Score": 5.17,
        "Time Score": 4.0,
        "Resource Cost": 2
    },
    {
        "Task": "Host opportunities for celebration, mourning, and foster a safe space",
        "Path Category": "Organized Divestment",
        "Scale": 7.44,
        "Skills": "R,SE,MOC",
        "Skill Cost": 1.505,
        "Solvability": 4.855,
        "Neglectedness": -5.0,
        "Impact Score": 5.79,
        "Time Score": 6.41,
        "Resource Cost": 1
    },
    {
        "Task": "Create systems to manage the flow and support the need of products and services",
        "Path Category": "Democratized Use of Resources",
        "Scale": 9.58,
        "Skills": ",RS,TMOVEC",
        "Skill Cost": 2.342,
        "Solvability": 41.275,
        "Neglectedness": -4.85,
        "Impact Score": 43.66,
        "Time Score": 8.82,
        "Resource Cost": 1
    },
    {
        "Task": "Halt the distribution of funds, products, or services to war criminals, fascists, and greedy capitalists",
        "Path Category": "Organized Divestment",
        "Scale": 10.0,
        "Skills": ",S,TMOVELDC",
        "Skill Cost": 2.71,
        "Solvability": 14.418,
        "Neglectedness": -5.09,
        "Impact Score": 16.62,
        "Time Score": 5.2,
        "Resource Cost": 1
    },
    {
        "Task": "Share and teach values and beliefs that form the foundation of resource sharing",
        "Path Category": "Democratized Use of Resources",
        "Scale": 9.0,
        "Skills": ",LDR,TMOEC",
        "Skill Cost": 2.127,
        "Solvability": 8.773,
        "Neglectedness": -5.65,
        "Impact Score": 10.0,
        "Time Score": 5.2,
        "Resource Cost": 1
    },
    {
        "Task": "Share knowledge and information on the stream of production and service by labor",
        "Path Category": "Democratized Use of Resources",
        "Scale": 9.56,
        "Skills": ",ECDR,TMOVL",
        "Skill Cost": 2.149,
        "Solvability": 10.052,
        "Neglectedness": -5.65,
        "Impact Score": 11.82,
        "Time Score": 5.2,
        "Resource Cost": 1
    },
    {
        "Task": "Institutionalize the knowledge of resource management and anti-greed work",
        "Path Category": "Policies Preventing Greed",
        "Scale": 11.95,
        "Skills": ",CED,TMOVLR",
        "Skill Cost": 2.352,
        "Solvability": 13.523,
        "Neglectedness": -5.35,
        "Impact Score": 17.78,
        "Time Score": 7.11,
        "Resource Cost": 1
    },
    {
        "Task": "Develop a rehabilitative justice system for greed ",
        "Path Category": "Policies Preventing Greed",
        "Scale": 13.0,
        "Skills": ",SO,TMVELDCR",
        "Skill Cost": 2.713,
        "Solvability": 24.012,
        "Neglectedness": -4.85,
        "Impact Score": 29.45,
        "Time Score": 6.41,
        "Resource Cost": 1
    },
    {
        "Task": "Act on knowledge of capitalist incentives that imprison others in a way defends, educates, and empowers labor",
        "Path Category": "Policies Preventing Greed",
        "Scale": 10.0,
        "Skills": ",,TMOVLDCR",
        "Skill Cost": 2.709,
        "Solvability": 18.03,
        "Neglectedness": -6.35,
        "Impact Score": 18.97,
        "Time Score": 4.82,
        "Resource Cost": 1
    },
    {
        "Task": "Strategize on broader campaigns and networks that widen the support of labor, liberty, and well-being",
        "Path Category": "Policies Preventing Greed",
        "Scale": 16.48,
        "Skills": ",ELDCRS,TMOV",
        "Skill Cost": 2.0,
        "Solvability": 15.406,
        "Neglectedness": -5.85,
        "Impact Score": 24.03,
        "Time Score": 6.8,
        "Resource Cost": 1
    }
]
