let gallery = [
  {
    path:"../img/ultraviolet/hidden_demon_02.jpg",
    title:"demon",
    keywords:"drawing color pencil",
    width: 1285,
    height: 1714,
  },
  {
    path:"../img/ultraviolet/biggest_sucker.jpg",
    title:"world's biggest sucker",
    keywords:"drawing graphite black and white blackandwhite black&white black & white",
    width: 1290,
    height: 1720,
  },
  {
    path:"../img/ultraviolet/hornboy_wip.jpg",
    title:"horn boy",
    keywords:"drawing graphite black and white blackandwhite black&white black & white",
    width: 1290,
    height: 1720,
  },
  {
    path:"../img/ultraviolet/honey_eye_collection.jpg",
    title:"eyes of honey",
    keywords:"drawing color pencil",
    width: 1440,
    height: 1800,
  },
  {
    path:"../img/ultraviolet/underwater_scene.jpg",
    title:"underwater scene",
    keywords:"drawing color pencil",
    width: 1225,
    height: 1633,
  },
  {
    path:"../img/ultraviolet/branches_and_glances.jpg",
    title:"eyes in branches",
    keywords:"drawing graphite black and white blackandwhite black&white black & white ink",
    width: 1285,
    height: 1714,
  },
  {
    path:"../img/ultraviolet/dyptych_lg_pour_black.jpg",
    title:"black ripple",
    keywords:"paint acryllic pour flow art flowart color",
    width: 1037,
    height: 1382,
  },
  {
    path:"../img/ultraviolet/dyptych_lg_pour_white.jpg",
    title:"white ripple",
    keywords:"paint acryllic pour flow art flowart color",
    width: 1225,
    height: 1633,
  },
  {
    path:"../img/ultraviolet/dyptych_blackripple.jpg",
    title:"black ripple",
    keywords:"paint acryllic pour flow art flowart color",
    width: 1536,
    height: 2048,
  },
  {
    path:"../img/ultraviolet/dyptych_whiteripple.jpg",
    title:"white ripple",
    keywords:"paint acryllic pour flow art flowart color",
    width: 1536,
    height: 2048,
  },
  {
    path:"../img/ultraviolet/snakehead_greenbg.jpg",
    title:"snakehead with a green background",
    keywords:"drawing graphite black and white blackandwhite black&white black & white paint acryllic pour",
    width: 843,
    height: 1124,
  },
  {
    path:"../img/ultraviolet/hummingbird_purpleborder_2.jpg",
    title:"hummingbird with a purple border",
    keywords:"drawing color pencil paint acryllic pour",
    width: 828,
    height: 1104,
  },
  {
    path:"../img/ultraviolet/hummingbird_crisp.jpg",
    title:"hummingbird",
    keywords:"drawing color pencil",
    width: 1536,
    height: 2048,
  },
  {
    path:"../img/ultraviolet/exalted_pose.jpg",
    title:"arms lifted",
    keywords:"drawing graphite black and white blackandwhite black&white black & white",
    width: 1285,
    height: 1715,
  },
  {
    path:"../img/ultraviolet/framed_cheeks.jpg",
    title:"framed cheek print",
    keywords:"color paint acryllic",
    width: 828,
    height: 1792,
  }
]
